[paths]
app_path = "{{ cookiecutter.name }}/app"
app_packages_path = "{{ cookiecutter.name }}/app_packages"
support_path = "Support"

icon.20 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-20.png"
icon.29 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-29.png"
icon.40 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-40.png"
icon.58 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-58.png"
icon.60 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-60.png"
icon.76 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-76.png"
icon.80 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-80.png"
icon.87 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-87.png"
icon.120 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-120.png"
icon.152 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-152.png"
icon.167 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-167.png"
icon.180 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-180.png"
icon.1024 = "{{ cookiecutter.name }}/Images.xcassets/AppIcon.appiconset/icon-1024.png"

splash.1024x748 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1024x748.png"
splash.1024x768 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1024x768.png"
splash.1125x2436 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1125x2436.png"
splash.1242x2208 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1242x2208.png"
splash.1242x2688 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1242x2688.png"
splash.1536x2008 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1536x2008.png"
splash.1536x2048 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1536x2048.png"
splash.1792x828 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-1792x828.png"
splash.2048x1496 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-2048x1496.png"
splash.2048x1536 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-2048x1536.png"
splash.2208x1242 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-2208x1242.png"
splash.2436x1125 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-2436x1125.png"
splash.2688x1242 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-2688x1242.png"
splash.640x1136 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-640x1136.png"
splash.640x960 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-640x960.png"
splash.750x1334 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-750x1334.png"
splash.768x1004 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-768x1004.png"
splash.768x1024 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-768x1024.png"
splash.828x1792 = "{{ cookiecutter.name }}/Images.xcassets/LaunchImage.launchimage/launch-828x1792.png"